# Generated by Django 5.1.6 on 2025-04-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_encrypt_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedembedding',
            name='identification',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
